# proj info
site_name: 'Krieger Wiki'
site_description: 'Wiki for Kriegerrand'
site_author: 'Dr. Krieger'
site_url: https://wiki.algersoft.org/

# repo
repo_name: 'Algersoft/krieger-documents'
repo_url: 'https://github.com/Algersoft/kriegers-documents'

# copyright
copyright: 'Copyright 2019 AlgerSoft'


# config
theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/fav.png'
  palette:
    primary: 'Blue'
    accent: 'light blue'
  language: 'en'
  direction: 'ltr'
  feature:
    tabs: true
  # 404 page
  static_templates:
    - 404.html
  extra_css:
    - stylesheets/extra.css

# customization
extra:
  search:
    language: 'en'
  social:
    - type: 'github'
      link: 'https://github.com/Algersoft'
    - type: 'twitter'
      link: 'https://twitter.com/kriegerrand'
    - type: 'telegram'
      link: 'https://t.me/kriegerrand'
    - type: 'discordapp'
      link: 'https://discord.gg/kpFYD88'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

  #pymdown extensions
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# directory org
nav:
    - Welcome:
      - Home: index.md
      - Getting Started: Getting-Started.md
      - About KREGR: about/Home.md
      - Wallets: wallets/Making-a-Wallet.md
      - Mining: mining/What-is-mining.md
      - Service Operators: service-operators/Resources.md
      - Glossary: guides/Glossary.md
    - About:
      - Home: about/Home.md
      - Features: about/Features.md
      - Our Community: about/Community.md                           
      - Contributing: about/Contributing.md                     
      - Technical Data: about/Technical-Data.md     
    - Wallets:
      - Making a Wallet: wallets/Making-a-Wallet.md
      - Paper Wallet: wallets/Making-a-paper-wallet.md
      - Recovering your Wallet: wallets/recovering-your-wallet.md
      - GUI Wallets:
        - Overview of GUI Wallets: wallets/Making-a-GUI-Wallet.md
    - Mining:
      - What is Mining ?: mining/What-is-mining.md
    - Guides:
      - FAQ / Common Sollutions: guides/FAQ-Sollutions.md
      - Glossary: guides/Glossary.md
