# proj info
site_name: 'Krieger Wiki'
site_description: 'Wiki for Kriegerrand'
site_author: 'Dr. Krieger'
site_url: https://wiki.algersoft.org/

# repo
repo_name: 'Algersoft/krieger-documents'
repo_url: 'https://github.com/Algersoft/kriegers-documents'

# copyright
copyright: 'Copyright 2019 AlgerSoft'


# config
theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/fav.png'
  palette:
    primary: 'Blue'
    accent: 'light blue'
  language: 'en'
  direction: 'ltr'
  feature:
    tabs: true
  # 404 page
  static_templates:
    - 404.html
  extra_css:
    - stylesheets/extra.css

# customization
extra:
  search:
    language: 'en'
  social:
    - type: 'github'
      link: 'https://github.com/Algersoft'
    - type: 'twitter'
      link: 'https://twitter.com/kriegerrand'
    - type: 'telegram'
      link: 'https://t.me/kriegerrand'
    - type: 'discordapp'
      link: 'https://discord.gg/kpFYD88'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

  #pymdown extensions
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# directory org
nav:
    - Welcome:
      - Home: index.md
      - Getting Started: Getting-Started.md
      - About KREGR: about/Home.md
      - Wallets: wallets/Making-a-Wallet.md
      - Mining: mining/What-is-mining.md
      - Service Operators: service-operators/Resources.md
      - Glossary: guides/Glossary.md
    - About:
      - Home: about/Home.md
      - Features: about/Features.md
      - Our Community: about/Community.md
      - Contributing: about/Contributing.md
      - Technical Data: about/Technical-Data.md
      - Branding: about/Branding.md
      - Timeline: about/Timeline.md
      - Licence: about/Licence.md
      - Sponsoring:
        - Sponsoring: about/Sponsoring.md
    - Wallets:
      - Making a Wallet: wallets/Making-a-Wallet.md
      - Paper Wallet: wallets/Making-a-paper-wallet.md
      - Recovering your Wallet: wallets/recovering-your-wallet.md
      - CLI Wallet:
        - Kriegerbank Overview: wallets/Kriegerbank-Overview.md
        - Using Kriegerbank: wallets/Kriegerbank-how-to-use.md
      - Krieger-RPC:
        - Overview of krieger-rpc: wallets/krieger-rpc-index.md
        - Command line Arguments: wallets/krieger-rpc-command-line.md
        - JSON RPC Api: wallets/krieger-json-api.md
        - JSON RPC erros: wallets/krieger-rpc-api-error-conditions.md
      - GUI Wallets:
        - Overview of GUI Wallets: wallets/Making-a-GUI-Wallet.md
        - Kriegerrand Wallet v2.0: wallets/KREGR-GUI-Desktop-Wallet-V2.md
        - Kriegerrand Electron Wallet v3.0: wallets/KREGR-GUI-Electron-Wallet.md
      - Remote Nodes:
        - Using Remote Nodes: wallets/Using-remote-nodes.md
    - Mining:
      - What is Mining ?: mining/What-is-mining.md
      - How to Mine KREGR: mining/How-to-mine-KREGR.md
      - Mining Pools: mining/Pools.md
      - In-browser Miner: mining/kriegerrand-in-browser-javascript-web-miner.md
      - Javascript Miner: mining/kriegerrand-javascript-miner.md
      - Mining on your Phone:
        - Mine Kriegerrand from mobile: mining/mobile-mining/Mining-with-Phone.md
        - Sleep Mining: mining/mobile-mining/Sleep-Mining.md
        - Mining with Kriegerrand Wallet iOS: mining/mobile-mining/Mining-with-KREGR-Wallet-iOS.md
      - Mining with Kriegerrand GUI Miner:
        - Introduction: mining/KREGR-GUI-Miner.md
        - How to use: mining/KREGR-GUI-Miner-using.md
        - How to compile: mining/KREGR-GUI-Miner-Compile.md
        - Update Details: mining/KREGR-GUI-Miner-Update.md
      - Mining with XMR-stak: 
        - What is XMR-stak: mining/XMR-Stak-index.md
        - Mining on Windows: mining/XMR-Stak-windows-Guide.md
        - Mining on Linux: mining/XMR-Stak-Linux-Guide.md
        - Mining on Mac OS: mining/XMR-Stak-Mac-Guide.md
      - Mining with XMRIG:
        - What is XMRIG: mining/XMRIG-index.md
        - CPU Mining on Linux: mining/XMRIG-Guide-cpu-linux.md
        - CPU Mining on Mac: mining/XMRIG-Guide-cpu-mac.md
        - CPU Mining on Windows: mining/XMRIG-Guide-cpu-windows.md
      - Mining with a SBC: mining/KREGR-Mining-Rasberry-Pi.md
    - Service Operators:
      - Ressources: service-operators/Resources.md
      - Compiling from Source: service-operators/Compiling-from-Source.md
      - Pool Operators: service-operators/Pool-Operator.md
      - MindBraind:
        - Overview: service-operators/MindBraind-Overview.md
        - Command Line Arguments: service-operators/MindBraind-daemon-arguments.md
        - Command Inline Options: service-operators/MindBraind-daemon-cli-options.md
        - JSON RPC API: service-operators/MindBraind-daemon-json-rpc-api.md
        - HTTP RPC API: service-operators/MindBraind-daemon-http-rpc-api.md
        - Using Checkpoints: service-operators/Using-checkpoints-for-MindBraind.md
    - Guides:
      - Dashboard:
        - Presentation: guides/dashboard/dashboard.md
      - Bounty Programm: guides/Bounty-Program.md
      - Glossary: guides/Glossary.md
